version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  frontend:
    image: node:18
    command: sh -c "npx create-react-app my-app && cd my-app && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - app_network
    volumes:
      - frontend_data:/usr/src/app

  backend:
    image: openjdk:17
    working_dir: /app
    command: sh -c "./mvnw spring-boot:run"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: always
    networks:
      - app_network
    volumes:
      - backend_data:/app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network
    volumes:
      - redis_data:/data

volumes:
  frontend_data:
  backend_data:
  db_data:
  redis_data:
